# syntax=docker/dockerfile:1

FROM public.ecr.aws/docker/library/ubuntu:24.04 AS base

# Neuron SDK components version numbers
ARG NEURONX_CC_VERSION=2.16.372.0
ARG NEURONX_FRAMEWORK_VERSION=2.5.1.2.4.0
ARG NEURONX_TRANSFORMERS_VERSION=0.13.380
ARG NEURONX_COLLECTIVES_LIB_VERSION=2.23.135.0-3e70920f2
ARG NEURONX_RUNTIME_LIB_VERSION=2.23.112.0-9b5179492
ARG NEURONX_DISTRIBUTED_VERSION=0.10.1
ARG NEURONX_DISTRIBUTED_INFERENCE_VERSION=0.1.1

ARG TORCHSERVE_VERSION=0.11.0

ENV VLLM_TARGET_DEVICE=neuron
ENV PYTHONUNBUFFERED=1

RUN <<EOT
  rm -f /etc/apt/apt.conf.d/docker-clean
  echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache
  echo 'APT::Install-Suggests "0";' >> /etc/apt/apt.conf.d/00-docker
  echo 'APT::Install-Recommends "0";' >> /etc/apt/apt.conf.d/00-docker
  echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

  apt-get update
  apt-get install -y \
    ca-certificates \
    gnupg2 \
    wget

  # TODO - when is noble supported?
  echo "deb https://apt.repos.neuron.amazonaws.com jammy main" > /etc/apt/sources.list.d/neuron.list
  # TODO - https://askubuntu.com/questions/1286545/what-commands-exactly-should-replace-the-deprecated-apt-key
  wget -qO - https://apt.repos.neuron.amazonaws.com/GPG-PUB-KEY-AMAZON-AWS-NEURON.PUB | apt-key add -
  apt-get update

  apt-get remove -y \
    wget
  apt-get autoremove
  apt-get clean
  rm -rf /var/lib/apt/lists/*
EOT

RUN <<EOT
  apt-get update
  apt-get install -y \
    python3.12 \
    python3-pip \
    python-is-python3

  apt-get autoremove
  apt-get clean
   rm -rf /var/lib/apt/lists/*
EOT

############################################################################################################

FROM base AS build

RUN <<EOT
  apt-get update
  apt-get install -y \
    aws-neuronx-collectives=${NEURONX_COLLECTIVES_LIB_VERSION} \
    aws-neuronx-runtime-lib=${NEURONX_RUNTIME_LIB_VERSION}

  apt-get autoremove
  apt-get clean
  rm -rf /var/lib/apt/lists/*
EOT

RUN <<EOT
  pip install --no-cache-dir --upgrade --extra-index-url https://pip.repos.neuron.amazonaws.com --break-system-packages \
    neuronx-cc==${NEURONX_CC_VERSION} \
    torch-neuronx==${NEURONX_FRAMEWORK_VERSION} \
    transformers-neuronx==${NEURONX_TRANSFORMERS_VERSION}

  pip install --no-cache-dir --upgrade --extra-index-url https://pip.repos.neuron.amazonaws.com --break-system-packages \
    neuronx_distributed==$NEURONX_DISTRIBUTED_VERSION \
    neuronx_distributed_inference==$NEURONX_DISTRIBUTED_INFERENCE_VERSION

EOT

ARG VLLM_VERSION=0.7.1

WORKDIR /tmp

RUN <<EOT
  apt-get update
  apt-get install -y \
    curl

  # pip install --no-cache-dir --break-system-packages \
  #   torchserve==${TORCHSERVE_VERSION}

  curl -sL https://github.com/vllm-project/vllm/releases/download/v${VLLM_VERSION}/vllm-${VLLM_VERSION}.tar.gz | tar xvz

  cd vllm-${VLLM_VERSION}
  pip install --no-cache-dir --break-system-packages --no-build-isolation -v -e .
  # rm -rf /tmp/*

  apt-get remove -y \
    curl
  apt-get autoremove
  apt-get clean
  rm -rf /var/lib/apt/lists/*
EOT
